# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       cinema

# >> macros
# << macros

Summary:    Hawaii desktop multimedia player.
Version:    0.0.0.20130708.769b527
Release:    1
Group:      Applications/System
License:    BSD
Source0:    cinema-%{version}.tar.bz2
#Source100:  cinema.yaml
Patch1:     cinema-install-patch.patch
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
#BuildRequires:  desktop-file-utils
Requires:       qt5-qtdeclarative-import-multimedia
#Requires:       qt5-qtmultimedia-plugin-mediaservice-audioengine

%description
Provides media player for Hawaii desktop


%prep
%setup -q -n cinema
#%patch1 -p1

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 cinema.pro

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

#desktop-file-install --delete-original       \
#  --dir %{buildroot}%{_datadir}/applications             \
#   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/cinema
%{_libdir}/qt5/qml/cinema/
# >> files
# << files
